### ISSUE TITLE
0.5.2 is not a proper release

### ISSUE THREAD

**Issue by bsiegert** [hfst/hfst-ospell#52]
Hi! pkgsrc maintainer here.

hfst-ospell 0.5.1 was a Github release with an official release tarball. For some reason, 0.5.2 is just a tag, so it does not show up under "Releases". In addition, the tarball does not contain the `configure` script, just `configure.ac`.

**Comment by TinoDidriksen** [comment]
https://github.com/hfst/hfst-ospell/releases/tag/v0.5.2 made a proper release.

There is no `configure`, and I don't want to distribute one: When building from source, one should build from actual source - autoconf generated files have a bad habit of bit-rotting, leading to many places having to work around ancient `configure` scripts. Much better to generate locally from `configure.ac`.

**Comment by flammie** [comment]
Surely uploading the tarballs from `make dist` *must* be easiest for all the distros, if some distro is silly enough not to make the default autotools generated tarball easiest to package can only blame themselves or just use the github-generated source-only zips or just git checkout...

**Comment by TinoDidriksen** [comment]
> Surely uploading the tarballs from `make dist` _must_ be easiest for all the distros...

* [OpenBSD port builds](https://www.openbsd.org/faq/ports/specialtopics.html) wholly replaces config.guess because it is known to bit-rot, and "_In most cases, patching configure directly is a bad idea._" and "_Configure scripts are big generated files. They are an ideal hiding place for trojan horses, and this has indeed already happened in the past._"
* [Debian guidelines](https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html#autotools) say "_This rebuilds all auto-generated files to the latest version and provides better support for porting to the newer architectures._"
* [Fedora guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/what-can-be-packaged/#_pregenerated_code) say "_Often a package will contain code which was itself generated by other code. This often takes the form of configure files..._" ... "_It is suggested, but not required, that such code be regenerated as part of the build process._"

There are very strong reasons against `make dist`. There are no particularly good reasons for it.

The only remaining reason for it that I can sort of see is when the `configure.ac` and `Makefile.am` files are tied to ancient versions of autotools, but that is not the case here - we have CI that tests multiple configurations, including bleeding edge and long term support.

**Comment by chenrui333** [comment]
bump the version in this PR, https://github.com/Homebrew/homebrew-core/pull/62994

But I did notice the artifact name got changed a bit (just call it out)

**Comment by TinoDidriksen** [comment]
> But I did notice the artifact name got changed a bit (just call it out)

Correct. Prior releases were not by me. I just uploaded the same .tar.bz2 that our build system produces, which is a cleaned up git clone.

**Comment by chenrui333** [comment]
Got you, thanks for confirming it!
